# Uncomment the next line to define a global platform for your project
# platform :ios, '12.0'

target 'Comando' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
pod 'SwiftOverlays', '~> 5.0.1'
pod 'Firebase/Core'
pod 'Firebase/Messaging'
  # Pods for Comando

end
